apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ${SERVICE}-hpa-${BUILD_TIMESTAMP}
  namespace: ${NAMESPACE}
  labels:
    app: ${SERVICE}
    env: ${ENVIRONMENT}
    version: ${IMG_TAG}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${SERVICE}-deployment-${BUILD_TIMESTAMP}
    namespace: ${NAMESPACE}
  minReplicas: ${API_MS_MIN_REPLICAS}
  maxReplicas: ${API_MS_MAX_REPLICAS}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
   scaleDown:
     stabilizationWindowSeconds: 300
     policies:
     - type: Pods
       value: 2
       periodSeconds: 15
   scaleUp:
     stabilizationWindowSeconds: 60
     policies:
     - type: Pods
       value: 2
       periodSeconds: 15