apiVersion: v1
kind: Secret
metadata:
  name: ${SERVICE}-secret-${BUILD_TIMESTAMP}
  namespace: ${NAMESPACE}
  labels:
    app: ${SERVICE}
    env: ${ENVIRONMENT}
    version: ${IMG_TAG}
  type: Opaque
data:
  mySecret: ${TEST_SECRET}
  myOtherSecret: ${TEST_SECRET_2}