apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${SERVICE}-service-account-${BUILD_TIMESTAMP}
  namespace: ${NAMESPACE}
  labels:
    app: ${SERVICE}
    env: ${ENVIRONMENT}
    version: ${IMG_TAG}