services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.0-597b6f20-SNAPSHOT
    container_name: elasticsearch
    profiles: ["only_if_not_cicd"]
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    healthcheck:
      test: curl -s http://localhost:9200/_cluster/health | grep -E '"status":"(green|yellow)"' || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:9.1.0-597b6f20-SNAPSHOT
    container_name: kibana
    profiles: ["only_if_not_cicd"]
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "${KIBANA_PORT:-9003}:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk

  otel_collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel_collector
    profiles: ["only_if_not_cicd"]
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otelCollector/otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4317:4317"
    depends_on:
      - elasticsearch
    networks:
      - elk
      - myapp_shared

networks:
  elk:
  myapp_shared:
    external: true